name: flake8 Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Flake8
        run: pip install flake8

      - name: Run Flake8
        id: flake8
        run: flake8 . || echo "::error::Quality errors found. Cannot proceed." && exit 1
