name: Flake8 Code Quality Check

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Flake8
        run: pip install flake8

      - name: Run Flake8
        run: |
          output=$(flake8 .)
          if [ -n "$output" ]; then
            echo "::error::Quality errors found. Cannot proceed."
            echo "$output"
            exit 1
          else
            echo "No quality errors found."
          fi
