name: Flake8 Code Quality Check

on:
  push:
    branches:
      - dev  # Runs Flake8 before pushing to dev
  pull_request:
    branches:
      - dev  # Runs Flake8 on PR from test to dev

jobs:
  lint:
    name: Run Flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.*'  # Use the latest Python 3 version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: flake8 .
