name: Feature Testing

on:
  pull_request:
    branches:
      - master  # Runs feature tests on PR from test to master

jobs:
  feature-test:
    name: Run Feature Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.*'  # Use the latest Python 3 version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install test dependencies

      - name: Run Feature Tests
        run: pytest tests/  # Run all tests inside the 'tests' folder
