name: Unit Tests and Feature Testing

on:
  pull_request:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest  # Install pytest explicitly
          if [ "$RUNNER_OS" == "Windows" ]; then
            pip install pywin32==308
          fi

      - name: Run unit tests
        run: pytest test.py

      - name: Run feature tests
        run: |
          # Add commands to run feature-specific tests here
          # For example, if you have a separate test file for feature tests:
          pytest feature_tests.py