name: Unit Tests, Merge to Master & Trigger Jenkins

on:
  pull_request:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest  # Install pytest explicitly
          if [ "$RUNNER_OS" == "Windows" ]; then
            pip install pywin32==308
          fi

      - name: Run unit tests
        run: pytest test.py

  merge-to-master:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.NOTGITHUB_TOKEN }}  # Ensure this secret exists in GitHub

      - name: Merge test into master
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout master
          git merge --no-ff test -m "Merging test branch into master after successful tests"
          git push origin master

      - name: Trigger Jenkins job for deployment
        run: |
          curl -X POST "http://localhost:8080//job/shoe-price-predictions/build" \
          --user "admin:${{ secrets.JENKINS_TOKEN }}"