name: Unit Tests and Merge to Master

on:
  pull_request:
    branches:
      - test
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest  # Install pytest explicitly
          if [ "$RUNNER_OS" == "Windows" ]; then
            pip install pywin32==308
          fi

      - name: Run unit tests
        run: pytest test.py

  merge-to-master:
    needs: test
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Debug event payload
        run: |
          echo "Event payload:"
          echo "${{ toJson(github.event) }}"

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GITHUB_TOKEN

      - name: Merge test into master
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout master
          git merge --no-ff test -m "Merging test branch into master after successful tests"
          if [ $? -ne 0 ]; then
            echo "Merge failed"
            exit 1
          fi
          git push origin master
          if [ $? -ne 0 ]; then
            echo "Push failed"
            exit 1
          fi