name: Feature Testing

on:
  pull_request:
    branches:
      - test  # Runs tests when PR is made from dev to test

jobs:
  feature-test:
    name: Run Feature Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.*'  # Use the latest Python 3 version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies for testing

      - name: Run Tests
        run: pytest tests/  # Runs all tests in the 'tests' folder
